# Generated by Django 3.2.5 on 2021-08-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210821_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='userqrcode',
            name='authenticator_secret_code',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
