# Generated by Django 3.2.5 on 2021-08-21 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userqrcode_authenticator_secret_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_user_qrcode', to='user.userqrcode'),
        ),
    ]
